apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale
  namespace: tailscale
  labels:
    app: tailscale
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
