apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      hostname: k8s-cluseter
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:latest
          envFrom:
            - configMapRef:
                name: tailscale
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale
                  key: TS_AUTHKEY
          volumeMounts:
            - name: tailscale
              mountPath: /var/lib/tailscale
      volumes:
        - name: tailscale
          persistentVolumeClaim:
            claimName: tailscale
